function y = FIR_lowpass_10(x)
%FIR_LOWPASS_10 对输入 x 进行滤波并返回输出 y。

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 17-Nov-2022 18:04:11

%#codegen

% 要通过此函数生成 C/C++ 代码，请使用 codegen 命令。有关详细信息，请键入 'help codegen'。

persistent Hd;

if isempty(Hd)
    
    % 设计滤波器系数时使用了以下代码:
    % % Equiripple Lowpass filter designed using the FIRPM function.
    %
    % % All frequency values are in Hz.
    % Fs = 48000;  % Sampling Frequency
    %
    % N     = 10;     % Order
    % Fpass = 3000;   % Passband Frequency
    % Fstop = 12000;  % Stopband Frequency
    % Wpass = 1;      % Passband Weight
    % Wstop = 1;      % Stopband Weight
    % dens  = 20;     % Density Factor
    %
    % % Calculate the coefficients using the FIRPM function.
    % b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
    %            {dens});
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [-0.0196112477325528 -0.0286446644379778 ...
        0.0128744307915927 0.124863719974687 0.256464256890334 0.315842592572361 ...
        0.256464256890334 0.124863719974687 0.0128744307915927 ...
        -0.0286446644379778 -0.0196112477325528]);
end

y = step(Hd,double(x));


% [EOF]
