function y = IIR_highpass_10(x)
%DOFILTER 对输入 x 进行滤波并返回输出 y。

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 18-Nov-2022 14:32:57

%#codegen

% 要通过此函数生成 C/C++ 代码，请使用 codegen 命令。有关详细信息，请键入 'help codegen'。

persistent Hd;

if isempty(Hd)
    
    % 设计滤波器系数时使用了以下代码:
    %
    % N    = 10;     % Order
    % F3dB = 6000;   % 3-dB Frequency
    % Fs   = 48000;  % Sampling Frequency
    %
    % h = fdesign.highpass('n,f3db', N, F3dB, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -2 1 1 -1.273359763036 0.800802646665708; 1 -2 1 1 ...
        -1.07054686399639 0.513981894219676; 1 -2 1 1 -0.942809041582063 ...
        0.333333333333333; 1 -2 1 1 -0.867596118765068 0.226966197819818; 1 -2 1 ...
        1 -0.832673473270674 0.177578118927698], ...
        'ScaleValues', [0.768540602425428; 0.646132189554016; ...
        0.569035593728849; 0.523640579146222; 0.502562898049593; 1]);
end

s = double(x);
y = step(Hd,s);

