function y = IIR_lowpass_10(x)
%DOFILTER 对输入 x 进行滤波并返回输出 y。

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 17-Nov-2022 18:02:00

%#codegen

% 要通过此函数生成 C/C++ 代码，请使用 codegen 命令。有关详细信息，请键入 'help codegen'。

persistent Hd;

if isempty(Hd)
    
    % 设计滤波器系数时使用了以下代码:
    %
    % N    = 10;     % Order
    % F3dB = 3000;   % 3-dB Frequency
    % Fs   = 48000;  % Sampling Frequency
    %
    % h = fdesign.lowpass('n,f3db', N, F3dB, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.7433911655525 0.887032999652695; 1 2 1 1 ...
        -1.57425622265844 0.703962656667262; 1 2 1 1 -1.45424358625158 ...
        0.574061915083955; 1 2 1 1 -1.37792369101677 0.491453855754655; 1 2 1 1 ...
        -1.34092645780358 0.451408339092306], ...
        'ScaleValues', [0.035910458525048; 0.0324266085022054; ...
        0.0299545822080925; 0.0283825411844721; 0.0276204703221808; 1]);
end

s = double(x);
y = step(Hd,s);

