function y = IIR_filter(x)
%DOFILTER 对输入 x 进行滤波并返回输出 y。

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 25-Nov-2022 02:08:23

%#codegen

% 要通过此函数生成 C/C++ 代码，请使用 codegen 命令。有关详细信息，请键入 'help codegen'。

persistent Hd;

if isempty(Hd)
    
    % 设计滤波器系数时使用了以下代码:
    %
    % N     = 14;     % Order
    % F3dB1 = 2000;   % First
    % F3dB2 = 8000;   % Second
    % Fs    = 44100;  % Sampling Frequency
    %
    % h = fdesign.bandpass('n,f3db1,f3db2', N, F3dB1, F3dB2, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -0.754406628588015 0.772304500321882; 1 0 -1 ...
        1 -1.84355800548027 0.922557005981943; 1 0 -1 1 -1.68745558480251 ...
        0.772862802815558; 1 0 -1 1 -0.718201522471296 0.466016350937003; 1 0 -1 ...
        1 -1.49191242562211 0.605125569987383; 1 0 -1 1 -0.82121746205236 ...
        0.315053307212761; 1 0 -1 1 -1.14272700209755 0.374087683657232], ...
        'ScaleValues', [0.383580789099913; 0.383580789099913; ...
        0.341852114800373; 0.341852114800373; 0.319840663800284; ...
        0.319840663800284; 0.312956158171384; 1]);
end

s = double(x);
y = step(Hd,s);

