function y = FIR_filter(x)
%FIR_FILTER 对输入 x 进行滤波并返回输出 y。

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 25-Nov-2022 02:09:46

%#codegen

% 要通过此函数生成 C/C++ 代码，请使用 codegen 命令。有关详细信息，请键入 'help codegen'。

persistent Hd;

if isempty(Hd)
    
    % 设计滤波器系数时使用了以下代码:
    % % FIR Window Bandpass filter designed using the FIR1 function.
    %
    % % All frequency values are in Hz.
    % Fs = 44100;  % Sampling Frequency
    %
    % N    = 14;       % Order
    % Fc1  = 2000;     % First Cutoff Frequency
    % Fc2  = 8000;     % Second Cutoff Frequency
    % flag = 'scale';  % Sampling Flag
    % Beta = 0.5;      % Window Parameter
    % % Create the window vector for the design algorithm.
    % win = kaiser(N+1, Beta);
    %
    % % Calculate the coefficients using the FIR1 function.
    % b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [0.00292841921479276 -0.0199138095158639 ...
        -0.0806607199148666 -0.125528373308032 -0.0915683908931249 ...
        0.0295000505320583 0.169217350177522 0.230834928236676 0.169217350177522 ...
        0.0295000505320583 -0.0915683908931249 -0.125528373308032 ...
        -0.0806607199148666 -0.0199138095158639 0.00292841921479276]);
end

y = step(Hd,double(x));


% [EOF]
